### ISSUE TITLE
Data source testing has always been pending

### ISSUE THREAD

**Issue by suners** [ubisoft/mobydq#367]
hi, 
My problem is similar to this one https://github.com/ubisoft/mobydq/issues/361, also checked the configuration and docker network by referring to the method here, still can't solve the problem, please help, thank you.

![image](https://github.com/ubisoft/mobydq/assets/8072446/b6a65093-0414-425a-b5bb-2c04fdc448a0)
![image](https://github.com/ubisoft/mobydq/assets/8072446/59e6185f-29fa-49a9-910d-d4d0f98219b4)
![image](https://github.com/ubisoft/mobydq/assets/8072446/adc10138-cac0-4e47-8d16-b2f43ad9c550)
![image](https://github.com/ubisoft/mobydq/assets/8072446/a4ed0564-ab82-4278-93d7-b11adcebbccf)
![image](https://github.com/ubisoft/mobydq/assets/8072446/92920b5c-7831-417a-b7e7-8e4e3d2274ff)

> docker-compose.yml 

```
version: "3.1"
services:
    db:
        container_name: mobydq-db
        restart: always
        image: mobydq-db
        build:
            context: ./db
        volumes:
            - db:/var/lib/postgresql/data
        env_file:
            - ./.env

    graphql:
        container_name: mobydq-graphql
        restart: always
        image: mobydq-graphql
        build:
            context: ./graphql
        volumes:
            - //var/run/docker.sock:/var/run/docker.sock
        env_file:
            - ./.env
        depends_on:
            - db

    app:
        container_name: mobydq-app
        restart: always
        image: mobydq-app
        build:
            context: ./app
        env_file:
            - ./.env
        depends_on:
            - graphql
        command: ["prod"]

    nginx:
        container_name: mobydq-nginx
        restart: always
        image: nginx:alpine
        volumes:
            - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/config/cert.pem:/etc/nginx/cert.pem
            - ./nginx/config/key.pem:/etc/nginx/key.pem
        ports:
            - 80:80
            - 443:443
        depends_on:
            - graphql

    scripts:
        container_name: mobydq-scripts
        restart: always
        image: mobydq-scripts
        build:
            context: ./scripts
            args:
                - MAIL_HOST=${MAIL_HOST}
                - MAIL_PORT=${MAIL_PORT}
                - MAIL_SENDER=${MAIL_SENDER}
                - MAIL_PASSWORD=${MAIL_PASSWORD}
                - MAIL_BASE_URL=${MAIL_BASE_URL}
        env_file:
            - ./.env
        depends_on:
            - graphql

networks:
    default:
        name: mobydq_network

volumes:
    db:
``` 

> docker-compose.test.yml 

```
version: "3.1"
services:
    db-cloudera:
        container_name: mobydq-test-db-cloudera
        image: mobydq-test-db-cloudera
        restart: always
        build:
            context: ./test/db-cloudera/
            dockerfile: Dockerfile
        expose:
            - 10000
        hostname: quickstart.cloudera
        privileged: true
        tty: true

    db-hortonworks:
        container_name: mobydq-test-db-hortonworks
        image: mobydq-test-db-hortonworks
        restart: always
        build:
            context: ./test/db-hortonworks/
            dockerfile: Dockerfile
        expose:
            - 10000
        hostname: sandbox-hdf.hortonworks.com
        privileged: true
        tty: true

    db-mariadb:
        container_name: mobydq-test-db-mariadb
        image: mobydq-test-db-mariadb
        restart: always
        build:
            context: ./test/db-mariadb/
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
        expose:
            - 3306

    db-mysql:
        container_name: mobydq-test-db-mysql
        image: mobydq-test-db-mysql
        restart: always
        build:
            context: ./test/db-mysql/
            dockerfile: Dockerfile
        environment:
            MYSQL_ROOT_PASSWORD: "1234"
        expose:
            - 3306

    db-oracle:
        container_name: mobydq-test-db-oracle
        image: mobydq-test-db-oracle
        restart: always
        build:
            context: ./test/db-oracle/
            dockerfile: Dockerfile
        environment:
            ORACLE_PWD: "1234-abcd"
        expose:
            - 1521

    db-postgresql:
        container_name: mobydq-test-db-postgresql
        image: mobydq-test-db-postgresql
        restart: always
        build:
            context: ./test/db-postgresql/
            dockerfile: Dockerfile
        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "1234"
            POSTGRES_DATABASE: "star_wars"
        expose:
            - 5432

    db-sql-server:
        container_name: mobydq-test-db-sql-server
        image: mobydq-test-db-sql-server
        restart: always
        build:
            context: ./test/db-sql-server/
            dockerfile: Dockerfile
        environment:
            ACCEPT_EULA: "Y"
            SA_PASSWORD: "1234-abcd"
        expose:
            - 1433

    test-scripts:
        container_name: mobydq-test-scripts
        image: mobydq-test-scripts
        build:
            context: .
            dockerfile: ./test/Dockerfile
        command: ["./run-tests.sh", "${TEST_CASE}", "${TEST_HOST}", "${TEST_PORT}"]
        depends_on:
          - db
          - graphql

    test-lint-python:
        container_name: mobydq-test-lint-python
        image: mobydq-test-lint-python
        build:
            context: .
            dockerfile: ./test/Dockerfile
        command: ["pylint", "scripts", "test"]
```

>  run command

```
 docker-compose -f docker-compose.yml -f docker-compose.dev.yml up db graphql app nginx
```
